export enum Icons {
  NUMPY = 'NUMPY',
  PANDAS = 'PANDAS',
  DOCKER = 'DOCKER',
  SCIKITLEARN = 'SCIKITLEARN',
  PYTHON = 'PYTHON',
  TENSORFLOW = 'TENSORFLOW',
  MATPLOTLIB = 'MATPLOTLIB',
  JAVACRIPT = 'JAVASCRIPT',
  TYPESCRIPT = 'TYPESCRIPT',
  CSS = 'CSS',
  HTML = 'HTML',
  REACT = 'REACT',
  GITHUB = 'GITHUB',
  JAVA = 'JAVA',
  FIGMA = 'FIGMA',
}
export default Icons;
